# Generated by Django 5.0.4 on 2024-04-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_account_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='my_profile',
        ),
    ]
