# Generated by Django 5.0.4 on 2024-04-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_setting_my_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='messages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='chat.groupmessage'),
            preserve_default=False,
        ),
    ]
